name: CD
on:
  push:
    branches:
      - main
    paths:
      - "**.ts"
      - "**.json"
jobs:
  update:
    if: github.repository_owner == 'PreMiD'
    name: Update Presences
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Update Presences
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: npm run presenceUpdater
