name: Compile and Lint
on:
  push:
    branches:
      - "main"
  pull_request:
jobs:
  compileLint:
    name: Compile and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: "*"
      - name: Use Node.js 16
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Compile changed files
        run: |
          git config --global core.quotePath false
          pnpm compile ${{ github.event_name }} $GITHUB_HEAD_REF
      - name: Check Lint
        run: pnpm lint:ci
